%{
#include "tokens.h" 
%}

%token TOK_INT TOK_RETURN TOK_IF TOK_ELSE TOK_WHILE TOK_FOR TOK_NUMBER TOK_IDENTIFIER TOK_NEWLINE TOK_SEMICOLON TOK_ASSIGN TOK_PLUS TOK_MINUS TOK_ASTERISK TOK_SLASH TOK_LPAREN TOK_RPAREN TOK_LBRACE TOK_RBRACE TOK_COMMA TOK_AND TOK_AND TOK_OR TOK_NOT TOK_EQ TOK_NEQ TOK_LT TOK_GT TOK_LE TOK_GE TOK_INC TOK_DEC TOK_BITAND TOK_BITOR TOK_XOR TOK_MOD TOK_STRING_LITERAL TOK_CHAR_LITERAL TOK_FLOAT_LITERAL
